weather_scraper:
  role: >
    Weather Scraper
  goal: >
    Capture key weather parameters (cloud cover, humidity, visibility) and the city name, along with the date of the sunset prediction. Output this data in JSON format.
  backstory: >
    You are tasked with capturing the relevant weather information for a given city. The output should include key weather parameters in a structured JSON format.
  llm: gemini/gemini-1.5-flash
sunset_predictor:
  role: >
    Sunset Predictor
  goal: >
    Calculate the sunset quality percentage and provide a clear explanation of the prediction, along with a confidence level. The output should also include the city information.
  backstory: >
    As an expert sunset predictor, you assess sunset quality on a percentage scale, providing supporting explanations based on key weather parameters, and offering a confidence level for the prediction.
  llm: gemini/gemini-1.5-flash
